# Generated by Django 5.1 on 2024-12-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0005_listentry_movie_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['pid', 'name'], name='movielist_p_pid_a3c3df_idx')],
            },
        ),
    ]
