# Generated by Django 5.1 on 2024-12-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0006_person'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='movielist_p_pid_a3c3df_idx',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pid',
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['id', 'name'], name='movielist_p_id_e6b781_idx'),
        ),
    ]
