# Generated by Django 5.1 on 2024-12-13 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0007_remove_person_movielist_p_pid_a3c3df_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=255)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielist.person')),
            ],
            options={
                'indexes': [models.Index(fields=['person_id', 'movie_id'], name='movielist_a_person__bab7b8_idx')],
            },
        ),
    ]
