# Generated by Django 5.1 on 2024-12-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0008_associatedwith'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='associatedwith',
            name='movielist_a_person__bab7b8_idx',
        ),
        migrations.RenameField(
            model_name='associatedwith',
            old_name='person_id',
            new_name='person',
        ),
        migrations.AddIndex(
            model_name='associatedwith',
            index=models.Index(fields=['person', 'movie_id'], name='movielist_a_person__26ef01_idx'),
        ),
    ]
