# Generated by Django 5.1 on 2025-02-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0009_remove_associatedwith_movielist_a_person__bab7b8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
