# Generated by Django 5.1 on 2025-05-06 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0010_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielist.listentry')),
            ],
        ),
        migrations.CreateModel(
            name='FavPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.CharField(max_length=255, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielist.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielist.user')),
            ],
        ),
        migrations.CreateModel(
            name='FavFilmOfPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielist.listentry')),
                ('favPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielist.favperson')),
            ],
        ),
    ]
