# Generated by Django 5.1 on 2025-05-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0011_favfilm_favperson_favfilmofperson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavFilmOfPerson',
            new_name='FavFilmsOfPerson',
        ),
    ]
