# Generated by Django 5.1 on 2025-11-23 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0012_rename_favfilmofperson_favfilmsofperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentry',
            name='simplified_rating',
            field=models.SmallIntegerField(choices=[(1, 'Bad'), (2, 'Below Average'), (3, 'Decent'), (4, 'Great'), (5, 'Amazing')], default=3),
        ),
        migrations.AlterField(
            model_name='favfilmsofperson',
            name='favPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_persons', to='movielist.favperson'),
        ),
    ]
